baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Accueil'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Archives'
pageRef = '/archives'
weight = 20

[[menus.main]]
name = 'Auteurs'
pageRef = '/authors'
weight = 30

[[menus.main]]
name = 'Poésie'
pageRef = '/poetry'
weight = 30

[[menus.main]]
name = 'Statistiques'
pageRef = '/stats'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
